name: PVPManager
main: com.MinceRetor.PVPManager.PVPManager
version: 1.0
api-version: 1.13
author: MinceRetor
depend:
- Vault
loadbefore:
- Vault
commands:
    pvpm:
      usage: /<command> [on,off,mode[normal,team],info]
      permission: pvpmanager.pvpm
      permission-message: You do not have permission!